---
author: "Nombre Completo Autor"
date: "27/10/2017"
documentclass: book
forprint: yes
fontsize: 12pt
geometry: margin = 2.5cm
bibliography:
- bib/library.bib
- bib/paquetes.bib
- bib/articulos.bib
metodobib: yes
biblio-style: plainnat
csl: acm-sig-proceedings-long-author-list.csl
link-citations: yes
output:
  html_document:
    df_print: paged
  pdf_document:
    keep_tex: no
    number_sections: yes
    citation_package: natbib
    fig_caption: yes
    template: latex/templateMemoriaTFE.tex
    includes: null
---



```{r include=FALSE}
knitr::opts_chunk$set(fig.path = 'figurasR/',
                      echo = FALSE, warning = FALSE, message = FALSE,
                      fig.pos="H",fig.align="center",out.width="95%",
                      cache=FALSE)

```


<!-- \setcounter{chapter}{2} -->
<!-- \setcounter{chapter}{2} escribir 2 para capítulo 3  -->
<!-- \pagenumbering{arabic} -->

\ifdefined\ifprincipal
\else
\setlength{\parindent}{1em}
\pagestyle{fancy}
\setcounter{tocdepth}{4}
\tableofcontents
<!-- \nocite{*} -->
\fi

\ifdefined\ifdoblecara
\fancyhead{}{}
\fancyhead[LE,RO]{\scriptsize\rightmark}
\fancyfoot[LO,RE]{\scriptsize\slshape \leftmark}
\fancyfoot[C]{}
\fancyfoot[LE,RO]{\footnotesize\thepage}
\else
\fancyhead{}{}
\fancyhead[RO]{\scriptsize\rightmark}
\fancyfoot[LO]{\scriptsize\slshape \leftmark}
\fancyfoot[C]{}
\fancyfoot[RO]{\footnotesize\thepage}
\fi
\renewcommand{\headrulewidth}{0.4pt}
\renewcommand{\footrulewidth}{0.4pt}


# Capítulo 1

*Revisión de la literatura científica específica del voleibol genérica aplicada a otros deportes. Aplicabilidad por estructura de la información disponible para el voleibol*

## La estadística en el deporte

La estadística es una disciplina que, a día de hoy, está presente en cualquier aspecto de nuestra vida. Todo a nuestro alrededor puede ser objeto de estudio. Estos estudios se realizan con el fin de obtener datos y conclusiones para poder conocer mejor nuestro entorno y hacernos la vida más fácil. Una de las aplicaciones de la estadística que en los últimos años ha tenido una gran relevancia es la estadística deportiva. 

La aplicación de la estadística al deporte tiene como objetivo principal analizar el rendimiento de un jugador o de un equipo, con el fin de reducir los errores que se producen a lo largo de un partido. Así nació lo que se conoce actualmente como *Sports Analytics*, una serie de estadísticas que proporcionan una ventaja competitiva a un equipo o individuo. Para poder elaborarlas, se utilizan métodos estadísticos que, además de ayudar a la recogida y organización de los datos en el desarrollo de los entrenamientos permiten a los entrenadores y cuerpos técnicos conocer si se han cumplido o no los objetivos planteados y así modificar el rendimiento de sus equipos. 

Todo esto es una forma de hacer que los aficionados estén al tanto de ese rendimiento por parte de los equipos. Con la cantidad de avances tecnológicos que se han desarrollado en los últimos años, se puede llegar a predecir todo tipo de eventos que podrían ocurrir en el mundo deportivo. Estos avances han ayudado a profundizar en otros ámbitos importantes relacionados con el deporte, tales como la salud, para la prevención de lesiones, marketing, para la elaboración de estrategias de comunicación más eficaces, e incluso en las casas de apuestas, para la construcción de modelos predictivos que utilizan para sus ofertas. 


## Estado del arte

Como hemos comentado antes, una forma de poder determinar si un equipo o un jugador va a ganar o perder un partido es aplicando modelos estadísticos a datos recogidos de experiencias anteriores, en este caso, de partidos ya finalizados. En el artículo @sanjurjo2015analisis se aplicó un modelo de regresión logística multivariable a una serie de partidos de fútbol, con el objetivo de saber si es posible predecir el resultado de transiciones ofensivas durante un partido. Se concluyó que, además de ser capaz de predecir ese resultado, también se pudo determinar qué variables influían más en estas predicciones.

Al igual que en el fútbol, se han estudiado modelos estadísticos en otros deportes como el voleibol. El voleibol es un deporte de equipo, en el que juegan 6 jugadores y cuyo objetivo es pasar el balón por encima de la red para conseguir que caiga en el suelo del campo contrario. De aquí podríamos sacar datos sobre jugadores, equipos completos e incluso sobre las ligas de cada país, para construir modelos que predigan el resultado de un punto o de un partido.

En voleibol hay muchos elementos técnicos tácticos que pueden ser objeto de estudio. De cada uno de ellos se puede realizar un análisis acerca de las posibles situaciones de fallo o acierto de ejecución, y con esos datos, construir variables y poder iniciar un estudio.

En el artículo @marelic1998influence se investigó la influencia de 5 elementos técnicos tácticos: bloqueo, defensa, saque, recepción del saque y remate, en la puntuación de un determinado partido. A partir de un modelo de regresión, se pudo ver qué elementos influían en mayor medida para que un equipo ganase un partido. 

Los jugadores de voleibol se distinguen por su posición en el campo. Principalmente, podemos distinguir las siguientes: colocador, receptor, bloqueador y líbero. En función de la acción en la que se encuentre el equipo (recepción o defensa) estas posiciones se vuelven algo más específicas.
Puesto que uno de los objetivos principales de utilizar la estadística en este deporte es llegar a construir un modelo que mida la eficacia de los jugadores de un equipo, podemos construir las variables de estudio en función de la posición de cada uno. De esta forma, se han utilizado también ciertos modelos estadísticos para estudiar el resultado de un partido a partir de esas variables.

En la Liga Turca de 2017, se aplicó un estudio de este tipo distinguiendo entre hombres y mujeres, en función de las posiciones de los jugadores en el campo. Se determinó que los resultados de los partidos se explicaban bien a través de este modelo de eficacia y dos años más tarde se confirmó la fiabilidad y validez de este estudio. @akarccecsme2017possible

Andrea Gabrio en su artículo *Bayesian hierarchical models for the prediction of volleyball results* @gabrio2021bayesian propuso un modelo jerárquico bayesiano para la predicción de las clasificaciones de los equipos nacionales de voleibol, que también permitía estimar los resultados de cada partido de la liga. Para ello construyó variables relacionadas con la efectividad de los elementos técnicos de saque y ataque, desde el punto de vista ofensivo, y de bloqueo y defensa desde el punto de vista defensivo. Esta termina comparando la capacidad de predicción de los dos modelos construidos en cuanto a la clasificación de los equipos de la liga y observa que hay pocas diferencias entre ellos y entre las clasificaciones observadas.





